-- DISPONIBILIZANDO O BANCO DE DADOS < ADRRBR01 >
USE CEP
GO

-- CRIANDO STORED PROCEDURE < SELECT PARA RECUPERAÇÃO DE TODOS OS ENDEREÇOS > POR CEP
CREATE PROCEDURE PC_RECUPERA_ENDERECO;1
   @CEP VARCHAR(8)
AS
   SELECT     A.ID_CEP
             ,F.UF
		     ,E.CIDADE
		     ,B.BAIRRO
		     ,A.CEP
		     ,C.TIPO
		     ,A.LOGRADOURO
		     ,D.REGIAO
		     ,A.ESPECIAL
		     ,A.NUMEROINICIAL
		     ,A.NUMEROFINAL
   FROM       CEPS            A
   INNER JOIN BAIRROS         B ON B.ID_BAIRRO         = A.FK_BAIRRO         
   INNER JOIN TIPOSLOGRADOURO C ON C.ID_TIPOLOGRADOURO = A.FK_TIPOLOGRADOURO 
   INNER JOIN REGIOES         D ON D.ID_REGIAO         = B.FK_REGIAO
   INNER JOIN CIDADES         E ON E.ID_CIDADE         = B.FK_CIDADE         
   INNER JOIN UFS             F ON F.ID_UF             = E.FK_UF             
   WHERE      A.CEP = @CEP
GO

-- CRIANDO STORED PROCEDURE < SELECT PARA RECUPERAÇÃO DE TODOS OS ENDEREÇOS > POR LOGRADOURO
CREATE PROCEDURE PC_RECUPERA_ENDERECO;2
   @TipoLogradouro VARCHAR(40),
   @Logradouro     VARCHAR(80)
AS
   SELECT     A.ID_CEP
             ,F.UF
		     ,E.CIDADE
		     ,B.BAIRRO
		     ,A.CEP
		     ,C.TIPO
		     ,A.LOGRADOURO
		     ,D.REGIAO
		     ,A.ESPECIAL
		     ,A.NUMEROINICIAL
		     ,A.NUMEROFINAL
   FROM       CEPS            A
   INNER JOIN BAIRROS         B ON B.ID_BAIRRO         = A.FK_BAIRRO         
   INNER JOIN TIPOSLOGRADOURO C ON C.ID_TIPOLOGRADOURO = A.FK_TIPOLOGRADOURO 
   INNER JOIN REGIOES         D ON D.ID_REGIAO         = B.FK_REGIAO
   INNER JOIN CIDADES         E ON E.ID_CIDADE         = B.FK_CIDADE         
   INNER JOIN UFS             F ON F.ID_UF             = E.FK_UF        
   WHERE      C.TIPO       LIKE @TipoLogradouro + '%' 
   AND        A.LOGRADOURO LIKE @Logradouro + '%' 
GO

-- CRIANDO VIEW DO < SELECT PARA RECUPERAÇÃO DE TODOS OS ENDEREÇOS >
CREATE VIEW VW_ENDERECOS 
AS  
   SELECT     A.ID_CEP
             ,F.UF
		     ,E.CIDADE
		     ,B.BAIRRO
		     ,A.CEP
		     ,C.TIPO
		     ,A.LOGRADOURO
		     ,D.REGIAO
		     ,A.ESPECIAL
		     ,A.NUMEROINICIAL
		     ,A.NUMEROFINAL
   FROM       CEPS            A
   INNER JOIN BAIRROS         B ON B.ID_BAIRRO         = A.FK_BAIRRO         
   INNER JOIN TIPOSLOGRADOURO C ON C.ID_TIPOLOGRADOURO = A.FK_TIPOLOGRADOURO 
   INNER JOIN REGIOES         D ON D.ID_REGIAO         = B.FK_REGIAO
   INNER JOIN CIDADES         E ON E.ID_CIDADE         = B.FK_CIDADE         
   INNER JOIN UFS             F ON F.ID_UF             = E.FK_UF 
GO


-- EXECUTANDO AS STORED PROCEDURES CRIADAS
PC_RECUPERA_ENDERECO;1 '5777140'

PC_RECUPERA_ENDERECO;2 'RUA', 'RAFAEL DE PROENCA';
PC_RECUPERA_ENDERECO;2 'AVENIDA', 'PAULISTA';
PC_RECUPERA_ENDERECO;2 'PRACA', 'DA REPUBLICA';
PC_RECUPERA_ENDERECO;2 '', 'VIEIRA DE MORAIS';
PC_RECUPERA_ENDERECO;2 '','JOAO SIMOES';















