
CREATE DATABASE CEP
GO

USE CEP
GO

-- UFS
CREATE TABLE UFS (
ID_UF INT        IDENTITY NOT NULL PRIMARY KEY,
UF    VARCHAR(2) DEFAULT '' NOT NULL)
GO

CREATE UNIQUE INDEX IDX_UFS_1 ON UFS(UF)
GO

-- CIDADES
CREATE TABLE CIDADES (
ID_CIDADE INT         IDENTITY NOT NULL PRIMARY KEY,
FK_UF     INT         DEFAULT 0 NOT NULL REFERENCES UFS(ID_UF),
CIDADE    VARCHAR(50) DEFAULT '' NOT NULL)
GO

CREATE UNIQUE INDEX IDX_CIDADES_1 ON CIDADES(FK_UF,CIDADE)
GO
CREATE INDEX IDX_CIDADES_2 ON CIDADES(FK_UF)
GO

-- REGIÕES
CREATE TABLE REGIOES (
ID_REGIAO INT         IDENTITY NOT NULL PRIMARY KEY,
REGIAO    VARCHAR(30) DEFAULT '' NOT NULL)
GO

CREATE UNIQUE INDEX IDX_REGIOES_1 ON REGIOES(REGIAO)
GO

-- BAIRROS
CREATE TABLE BAIRROS (
ID_BAIRRO  INT        IDENTITY NOT NULL  PRIMARY KEY,
FK_CIDADE INT         DEFAULT 0 NOT NULL REFERENCES CIDADES(ID_CIDADE),
FK_REGIAO INT         DEFAULT 0 NOT NULL REFERENCES REGIOES(ID_REGIAO),
BAIRRO    VARCHAR(50) DEFAULT '' NOT NULL)
GO

CREATE UNIQUE INDEX IDX_BAIRROS_1 ON BAIRROS(FK_CIDADE,BAIRRO)
GO
CREATE INDEX IDX_BAIRROS_2 ON BAIRROS(FK_CIDADE)
GO
CREATE INDEX IDX_BAIRROS_3 ON BAIRROS(FK_REGIAO)
GO


-- TIPOS DE LOGRADOURO
CREATE TABLE TIPOSLOGRADOURO (
ID_TIPOLOGRADOURO INT         IDENTITY NOT NULL PRIMARY KEY,
TIPO              VARCHAR(40) DEFAULT '' NOT NULL)
GO

CREATE UNIQUE INDEX IDX_TIPOSLOGRADOURO_1 ON TIPOSLOGRADOURO(TIPO)
GO

-- CEPS
CREATE TABLE CEPS (
ID_CEP             INT         IDENTITY NOT NULL  PRIMARY KEY,
FK_BAIRRO          INT         DEFAULT 0 NOT NULL REFERENCES BAIRROS(ID_BAIRRO),
FK_TIPOLOGRADOURO  INT         DEFAULT 0 NOT NULL REFERENCES TIPOSLOGRADOURO(ID_TIPOLOGRADOURO),
CEP                VARCHAR(8)  DEFAULT '' NOT NULL,
LOGRADOURO         VARCHAR(80) DEFAULT '' NOT NULL,      
NUMEROINICIAL      INT         DEFAULT 0 NOT NULL,
NUMEROFINAL        INT         DEFAULT 0 NOT NULL,
PARIMPAR           INT         DEFAULT 0 NOT NULL,
ESPECIAL           INT         DEFAULT 0 NOT NULL,
ORIGEM             VARCHAR(30) DEFAULT '' NOT NULL,
LOGRADOUROPESQUISA VARCHAR(80) DEFAULT '' NOT NULL)
GO

CREATE UNIQUE INDEX IDX_CEPS_1 ON CEPS(CEP)
GO
CREATE INDEX IDX_CEPS_2 ON CEPS(FK_BAIRRO)
GO
CREATE INDEX IDX_CEPS_3 ON CEPS(FK_TIPOLOGRADOURO)
GO
CREATE INDEX IDX_CEPS_4 ON CEPS(LOGRADOURO)
GO

-------------
-- OPCIONAIS
-------------
-- PESQUISA NAS TABELAS
SELECT * FROM CEPS
SELECT * FROM TIPOSLOGRADOURO
SELECT * FROM BAIRROS
SELECT * FROM REGIOES
SELECT * FROM CIDADES
SELECT * FROM UFS

-- ORDEM PARA ELIMINAÇÃO DOS REGISTROS NAS TABELAS
DELETE FROM CEPS
DELETE FROM TIPOSLOGRADOURO
DELETE FROM BAIRROS
DELETE FROM REGIOES
DELETE FROM CIDADES
DELETE FROM UFS

-- ORDEM PARA ELIMINAÇÃO DAS TABELAS
DROP TABLE CEPS
DROP TABLE TIPOSLOGRADOURO
DROP TABLE BAIRROS
DROP TABLE REGIOES
DROP TABLE CIDADES
DROP TABLE UFS
